### PR TITLE
Mercurial coloring fix

### PR DESCRIPTION
**Pull request by mtrp12**
Support for mercurial was not working out of the box on Ubuntu 18.04. Thus this pull request. Some more justification in comment section.

### CODE REVIEW

**Comment by sn0cr** [comment]
Hi @mtrp12,

could you include the now changed master and then I'll can merge it.

**Comment by mtrp12** [comment]
Originally, the feature of the prompt, if I understand correctly, was to show red background for add/remove/modify/missing(removed by os command but still tracked), yellow if there are only untracked files in the directory and green for others(nothing to do). In my pull request, i combined untracked option with first condition, that is add/remove etc. I did it so that it behaves like the git prompt in the same file. Do you accept this change? The update will be different based on your decision.

Also, after looking at the new code in master, i feel like the author misinterpreted the meaning of "!" symbol. In mercurial it means missing file only. But the symbol is not returned here by a mercurial command but an extension namely hg-prompt. According to the wiki of the extension, mentioned in a previous comment, "!" also signifies add/modify. So, while at the end it works out for the user, it may be confusing for other reviewers. I would like to propose changing _color_hg_removed_bg_  to _color_hg_changed_bg_.

I will be awaiting your comment.

PS: For now I included the necessary changes, assuming your decision to be 'yes' and 'ok' respectively. I am new to git/github, so, let me know if I have done it incorrectly.

**Comment by sn0cr** [comment]
Your changes are looking good, however we have some merge conflicts, could you resolve them and push again? (i.e., `git merge master`  and here you are free to keep the commit message 😉)

**Comment by mtrp12** [comment]
I already merged master before. Why did it cause conflict? As you can see the latest merge commit has 0 changes.

**Comment by tkindy** [comment]
@sn0cr any word here? Looks like those merge conflicts were fixed.

**Pull request merged**
