### PR TITLE
Generalize virtual environment to support Nix shell

### PR DESCRIPTION
**Pull request by bakhtiyarneyman**

### CODE REVIEW

**Comment by sn0cr** [comment]
The only thing I'm currently thinking about is, if we should put each environment into its own segment. Then it would be easier to distinguish which type of environment is currently active.
Any thoughts about that? You might also want to add this feature to the Readme if you want 😉

**Comment by bakhtiyarneyman** [comment]
That's what I started with, but ultimately changed direction because I wan't sure how to proceed with respect to colors. I thought that it's probably not scalable to continue adding segments in this fashion. I also thought that it's unlikely that a person uses both python and nix environments in their day-to-day life, so it's better to group them.

I'm happy to implement what you propose if you tell me what color I should choose.

**Comment by sn0cr** [comment]
Oh yeah that's a good point, right now I'm not using NixOS but heard multiple times of it. 
Do you mind to add a description about the new feature to the readme? I will then merge it soon.

**Comment by bakhtiyarneyman** [comment]
Will do so tonight.

**Comment by bakhtiyarneyman** [comment]
Done. Thank you for the review!

**Comment by sn0cr** [comment]
Thank you for your contribution and making this theme better.

**Pull request merged**
